version: 2.1

jobs:
  build:
    docker:
      - image: node:14.16-alpine
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --frozen-lockfile
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build Docker image
          command: |
            docker build -t my-react-app .
            docker images
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag my-react-app "$DOCKER_USERNAME/my-react-app"
            docker push "$DOCKER_USERNAME/my-react-app"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: docker-creds
