version: 2.1

jobs:
  build:
    docker:
      - image: node:14.16-alpine
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --frozen-lockfile
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build Docker image
          command: |
            docker build -t jedla/frontend .
            docker images
      - run:
          name: test
          command: docker run jedla/frontend npm run test -- --coverage

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: docker-creds
